### PR TITLE
Improved Layout

### PR DESCRIPTION
**Pull request by unstablebrainiac**
**_Learning how to work with pull requests and contribute to public repos**_

Created a website-like layout for UserDetailsActivity
Improved layout for items in RecyclerView
Added TextInputLayout to searchQueryEt in HomeActivity

### CODE REVIEW

**Review by ashkhn — CHANGES_REQUESTED** [review]
Nice! 
Might as well update library versions..

**Comment by sajalnarang** [comment]
Isn't 24.2.1 the latest?

**Review by ashkhn — CHANGES_REQUESTED** [review]
You would also need to update retrofit and okhttp.. Also add a dependency for picasso

**Comment by unstablebrainiac** [comment]
I wonder why it works without the picasso dependency

**Review by ashkhn — APPROVED** [review]

**Comment by ashkhn** [comment]
It shouldn't build? I haven't pulled the changes and tested but it looks fine now

**Pull request merged**
